export enum ENV {
  // GENERAL
  NODE_ENV = 'NODE_ENV',
  PORT = 'PORT',
  APP_URL = 'APP_URL',

  // DATABASE CONFIG
  MONGO_URI = 'MONGO_URI',
  MONGO_DB_NAME = 'MONGO_DB_NAME',
  LOCAL_DATABASE_URL = 'LOCAL_DATABASE_URL',
  DATABASE_URL = 'DATABASE_URL',
  PG_HOST = 'PG_HOST',
  PG_PORT = 'PG_PORT',
  PG_USER = 'PG_USER',
  PG_PASSWORD = 'PG_PASSWORD',
  PG_DATABASE = 'PG_DATABASE',

  // AUTHENTICATION / JWT
  JWT_SECRET = 'JWT_SECRET',
  JWT_REFRESH_SECRET = 'JWT_REFRESH_SECRET',
  JWT_ACCESS_SECRET = 'JWT_ACCESS_SECRET',
  JWT_REFRESH_EXPIRES = 'JWT_REFRESH_EXPIRES_IN',
  JWT_ACCESS_EXPIRES = 'JWT_ACCESS_EXPIRES',
  HTTP_ONLY = 'HTTP_ONLY',

  // EMAIL SERVICE
  EMAIL_SERVICE = 'EMAIL_SERVICE',
  EMAIL_USERNAME = 'EMAIL_USERNAME',
  EMAIL_PASSWORD = 'EMAIL_PASSWORD',
  EMAIL_FROM = 'EMAIL_FROM',

  // THIRD PARTY API KEYS
  GOOGLE_API_KEY = 'GOOGLE_API_KEY',
  STRIPE_SECRET_KEY = 'STRIPE_SECRET_KEY',
  STRIPE_PUBLIC_KEY = 'STRIPE_PUBLIC_KEY',
  NAME_SPACE = 'NAME_SPACE',

  // FIREBASE
  FIREBASE_API_KEY = 'FIREBASE_API_KEY',
  FIREBASE_AUTH_DOMAIN = 'FIREBASE_AUTH_DOMAIN',
  FIREBASE_PROJECT_ID = 'FIREBASE_PROJECT_ID',
  FIREBASE_STORAGE_BUCKET = 'FIREBASE_STORAGE_BUCKET',
  FIREBASE_MESSAGING_SENDER_ID = 'FIREBASE_MESSAGING_SENDER_ID',
  FIREBASE_APP_ID = 'FIREBASE_APP_ID',

  // RAZORPAY CONFIGURATION
  RAZORPAY_KEY_ID = 'RAZORPAY_KEY_ID',
  RAZORPAY_KEY_SECRET = 'RAZORPAY_KEY_SECRET',

  // CORS CONFIGURATION
  CORS_ORIGIN = 'CORS_ORIGIN',

  // REDIS CONFIG
  REDIS_HOST = 'REDIS_HOST',
  REDIS_PORT = 'REDIS_PORT',
  REDIS_PASSWORD = 'REDIS_PASSWORD',

  // NATS / QUEUE SYSTEM
  NATS_URL = 'NATS_URL',

  // DEBUG LOGGING
  DEBUG = 'DEBUG',

  // FILE UPLOAD (CLOUDINARY)
  CLOUDINARY_URL = 'CLOUDINARY_URL',
  CLOUDINARY_CLOUD_NAME = 'CLOUDINARY_CLOUD_NAME',
  CLOUDINARY_API_KEY = 'CLOUDINARY_API_KEY',
  CLOUDINARY_API_SECRET = 'CLOUDINARY_API_SECRET',

  // OTHERS
  SESSION_SECRET = 'SESSION_SECRET',
  SESSION_COOKIE_SECURE = 'SESSION_COOKIE_SECURE',
  SESSION_COOKIE_MAXAGE = 'SESSION_COOKIE_MAXAGE',
  SESSION_COOKIE_SECRET = 'SESSION_COOKIE_SECRET',
}
